version: "3"  
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db
    ports:
      - "7017:27017"
    networks:
      - app-network
  code:
    container_name: code
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: masterji_app
    ports:
      - "3007:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    environment:
      - DB_HOSTNAME=mongodb
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
