version: "3"
# contaier
services:
  node:
    container_name: nodeapp
    image: nodeapp
    build:
      context: .
      dockerfile: node.dockerfile
      args:
        PACKAGES: "nano wget curl"
    ports:
      - "7171:3000"
    networks:
      - nodeapp-network
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - nodeapp-network
    port: 
      - "27017:27017"
networks:
  nodeapp-network:
    driver: bridge
docker engine.
docker dong goi ung dung de quang li image



