version: "3.1"

services:
  
  mongodb:
    container_name: mongo_pham
    image: mongo
    restart: always
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - ./data/db:/data/db
    ports: 
      - 27018:27017

  tin_app:
    depends_on:
      - mongodb
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: masterji_app
    ports:
      - 3007:3000
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
